version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /flask-app-peewee/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /flask-app-peewee/docker-credentials/password
    DOCKER_REGISTRY_URL: /flask-app-peewee/docker-credentials/url
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install flask
  build:
    commands:
      - echo "Running tests..."
      - cd app/
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/app:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'