version: "3.8"
services:
  flask_app:
    build: .
    ports:
    - "5000:5000"
    environment:
      DB_USERNAME: ${USERNAME}
      DB_DATABASE: ${DATABASE}
      DB_HOST: ${HOST}
      DB_PORT: ${PORT}
      DB_PASSWORD: ${PASSWORD}

  psql_test_db:
    image: postgres:13.4
    container_name: test-container
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}

    ports:
      - "5433:5432"
      
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d 