version: "3.8"
services:
  flask_app:
    build: .
    ports:
    - "5000:5000"
    environment:
      USERNAME: ${USERNAME}
      DATABASE:  ${DATABASE}
      HOST:  ${HOST}
      PORT:  ${PORT}
      PASSWORD: ${PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_HOST: ${POSTGRES_HOST}
      # POSTGRES_PORT: ${POSTGRES_PORT}
      # POSTGRES_DB: ${POSTGRES_DB}
      depends_on:
      - test_db
    
  test_db:
    image: postgres:13.4
    container_name: test-container
    restart: always

    ports:
      - "5433:5432"
      
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d 