version: "3.8"
services:
  flask_app:
    build: .
    ports:
    - "5000:5000"
  networks:
    - ksb-s_api_default 


  psql_test_db:
    image: postgres:13.4
    container_name: test-container
    restart: always      

    ports:
      - "5433:5432"
      
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d 
    networks:
    - ksb-s_api_default 