version: "3.8"
services:
  flask_app:
    build: .
    ports:
    - "5000:5000"
    environment:
      USERNAME: ${USERNAME}
      DATABASE:  ${DATABASE}
      HOST:  ${HOST}
      PORT:  ${PORT}
      PASSWORD: ${PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: 5432
      POSTGRES_HOST: psql_test_db


  psql_test_db:
    image: postgres:13.4
    container_name: test-container
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: 5432
      POSTGRES_HOST: psql_test_db
      

    ports:
      - "5433:5432"
      
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d 