version: "3.8"
services:
    
  test_db:
    image: postgres:13.4
    container_name: test-container
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d 
 
  flask_app:
    image: flask-app
    ports:
    - "5000:5000"
    environment:
      ENVIRONMENT: "test"
      USERNAME: ${USERNAME}
      DATABASE:  ${DATABASE}
      HOST:  ${HOST}
      PORT:  ${PORT}
      PASSWORD: ${PASSWORD}
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: ${POSTGRES_USER}

    depends_on:
    - test_db