name: Flask App

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Docker using Docker's official script
        run: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
        continue-on-error: false
      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
        continue-on-error: false
  
      - name: Start Services
        run: docker-compose up 
  
      - name: Run Tests
      
            
        run: |
          cd tests
          pytest  
          echo "successfully ran tests"

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          IP_ADDRESS: ${{ secrets.EC2_HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}



        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${USER_NAME}@${IP_ADDRESS} 'bash -s' << 'EOF'
            # Install Git and other dependencies
            sudo yum update -y
            sudo yum install -y git

          # Install Docker
            sudo yum update -y
            sudo yum install -y docker
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo usermod -aG docker ec2-user
            
    
          # Install Docker Compose
            if ! command -v docker-compose &> /dev/null
            then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            echo "Docker installed"
          

          # Clone or update repo
          if [ ! -d "/home/ec2-user/KSB-s_API" ]; then
              git clone https://github.com/Harriet-Hall/KSB-s_API.git /home/ec2-user/KSB-s_API
          else
              cd /home/ec2-user/KSB-s_API
              git fetch origin main
              git reset --hard origin/main  # Ensure the latest version is used
              git pull origin main
          fi

          cd /home/ec2-user/KSB-s_API

          # Set up virtual environment
          python3 -m venv venv
          source venv/bin/activate

          # Install dependencies 
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo yum install aws-cli

          # Docker compose 
          docker-compose down
    
          docker-compose up
          echo "App deployed to EC2"
          EOF

         
