name: Flask App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Docker using Docker's official script
        run: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
        continue-on-error: false
      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
        continue-on-error: false
  
      - name: Start Services
        run: docker-compose up -d
  
      # - name: Run Tests
      #   env:
      #     POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      #     POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
      #     POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      #     POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }} 
      #     POSTGRES_PORT: ${{ secrets.POSTGRES_HOST }} 

            
      #   run: |
      #     cd tests
      #     pytest  
      #     echo "successfully ran tests"

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          IP_ADDRESS: ${{ secrets.EC2_HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
          POSTGRES_DATABASE: ${{ secrets.DATABASE }}
          POSTGRES_USER: ${{ secrets.USER }}
          POSTGRES_HOST: ${{ secrets.HOST }}
          POSTGRES_PORT: ${{ secrets.PORT }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${USER_NAME}@${IP_ADDRESS} 'bash -s' << 'EOF'
            # Install Git and other dependencies
            sudo yum update -y
            sudo yum install -y git

          # Install Docker
            if ! command -v docker &> /dev/null
            then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo usermod -aG docker ec2-user
            newgrp docker
          fi
    
          # Install Docker Compose
            if ! command -v docker-compose &> /dev/null
            then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            cd /home/ec2-user/KSB-s_API

          # Stop existing containers (if any)
            docker-compose down
  
            # Build and run the Docker container
            docker-compose up --build -d
      
            echo "App deployed to EC2"
          EOF

         
