name: Flask App

on:
  push:
    branches:
      - workflow_dispatch

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Docker using Docker's official script
        run: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
        continue-on-error: false
      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
        continue-on-error: false
  
      # - name: Start Services
      #   run: docker-compose up 
  
      # - name: Run Tests
      
            
      #   run: |
      #     cd tests
      #     pytest  
      #     echo "successfully ran tests"

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          IP_ADDRESS: ${{ secrets.EC2_HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key ${USER_NAME}@${IP_ADDRESS} 'bash -s' << 'EOF'
            # Clone or update repo on EC2
            if [ ! -d "/home/ec2-user/KSB-s_API" ]; then
                git clone https://github.com/Harriet-Hall/KSB-s_API.git /home/ec2-user/KSB-s_API
            else
                cd /home/ec2-user/KSB-s_API
                git fetch origin main
                git reset --hard origin/main
                git pull origin main
            fi
            
            # Install Docker on EC2 if it's not installed
            sudo yum update -y
            sudo yum install -y docker
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo usermod -aG docker ec2-user
            
            # Install Docker Compose
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      
            # Run docker-compose
            cd /home/ec2-user/KSB-s_API

            docker stop $(docker ps -aq) 
            docker rm $(docker ps -aq)  
            docker rmi $(docker images -q)  
            docker-compose build --no-cache
            docker-compose up -d
            
          EOF