name: Test and deploy flask app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Docker
        uses: docker/setup-buildx-action@v2


      - name: Create .env file
        run: |

          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

      - name: Build and start containers
        env:
          ENVIRONMENT: test
        run: |
          docker build --target builder -t flask-app .
          docker compose --env-file .env up -d
          sleep 5
          
      - name: Run tests
        run: docker exec -i ksb-s_api-flask_app-1 pytest
        continue-on-error: false 

      - uses: actions/checkout@v2
      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $username -p $password 

      - name: build the docker image
        id: build-docker-image
        run: docker build --target production -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-peewee-app:latest .

      - name: Push the docker image
        id: push-docker-image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/flask-peewee-app:latest

      - name: Stop containers
        run: docker stop $(docker ps -q) 
      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and pull image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ec2-user  
          key: ${{ secrets.EC2_PRIVATE_KEY }}  
          script: |
            sudo yum update -y
            sudo yum install -y docker
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo usermod -aG docker ec2-user
            sudo docker stop $(docker ps -a -q)
            sudo docker rm $(docker ps -a -q)
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-peewee-app:latest
            sudo docker run -d -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/flask-peewee-app:latest
