name: Test and deploy flask app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_setup:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.4
        ports:
          - 5432:5432
        env:
          user: test_user
          password: test_password
          host: postgres
          port: 5432
          database: postgres

        options: >-
          --health-cmd="pg_isready -U test_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Docker
        uses: docker/setup-buildx-action@v2


      - name: Create .env file
        run: |

          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
 

      - name: Build and start containers
        run: |
          docker compose up -d --env-file .env
          docker compose ps
          sleep 5
          docker exec -i ksb-s_api-flask_app-1 pytest

      - name: Stop containers
        run: docker compose down


